services:
  weather-php:
    container_name: "weather-php"
    image: weather-php:latest
    build:
      context: .
      dockerfile: php/Dockerfile
      tags:
        - latest
    user: 1000:1000
    volumes:
      - ../../log:/var/weather/log
      - "$PWD/..:/var/weather"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
    name: weather-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:1:22::/112
          gateway: fd00:1:22::1

volumes:
  weather-db:
